hf_models:
- "hkuds/easyrec-roberta-small"
- "hkuds/easyrec-roberta-base"
- "hkuds/easyrec-roberta-large"
- "jibala-1022/easyrec-small"
- "jibala-1022/easyrec-base"
- "jibala-1022/easyrec-large"
production_data: "prod_data"
dataset: "tmdb_5000_movies.csv"
processed_dataset: "tmdb_5000_movies_processed.csv"
movie_embeddings: "movie_embeddings"